version: '3.8'

services:
  app:
    image: sahillathwal/rtft:latest
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix 
      - /etc/localtime:/etc/localtime:ro 
      - .:/app 
      - /var/run/docker.sock:/var/run/docker.sock 
      - /dev/input:/dev/input
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db

  dashboard:
    image: sahillathwal/rtft:latest
    command: [ "python", "dashboard/app.py" ]
    ports:
      - "8050:8050"
    depends_on:
      - app
    restart: always

volumes:
  mongodb_data:
