version: '3.8'

services:
  app:
    image: sahillathwal/rtftv2:latest
    container_name: rtftv2_app
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 socket for GUI access
      - /etc/localtime:/etc/localtime:ro  # Sync container timezone with host
      - .:/app  # Mount the project directory for development
      - /var/run/docker.sock:/var/run/docker.sock  # Enable access to Docker inside the container
      - /dev/input:/dev/input  # Access input devices (if needed)
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpass
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db

  # dashboard:
  #   image: sahillathwal/rtftv2:latest
  #   container_name: rtftv2_dashboard
  #   command: ["python3", "dashboard/app.py"]
  #   environment:
  #     - DISPLAY=${DISPLAY}
  #     - QT_X11_NO_MITSHM=1
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - NVIDIA_DRIVER_CAPABILITIES=all
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix  # Enable GUI access
  #   ports:
  #     - "8050:8050"
  #   depends_on:
  #     - app
  #   restart: always
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

volumes:
  mongodb_data:
    driver: local
