version: '3.8'

services:
  app:
    image: sahillathwal/rtft:latest
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: always

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db

  dashboard:
    image: sahillathwal/rtft:latest
    command: ["python", "dashboard/app.py"]
    ports:
      - "8050:8050"
    depends_on:
      - app
    restart: always

volumes:
  mongodb_data: