# RTSP Camera Configuration
RTSP_URL: "rtsp://USERNAME:PASSWORD@CAMERA_IP:PORT"

# Database Configuration
DATABASE:
  TYPE: "mongodb"
  HOST: "mongodb://localhost:27017/"
  NAME: "footfall_db"

# General Settings
SETTINGS:
  FRAME_WIDTH: 1920
  FRAME_HEIGHT: 1080
  FPS: 15
